IF NOT EXISTS (SELECT *FROM INFORMATION_SCHEMA.TABLES  WHERE TABLE_NAME = 'OBJECT_METADATA')
  BEGIN
      EXECUTE ('CREATE TABLE OBJECT_METADATA
      ( OBJECT_UID INT,
        OBJECT_TYPE VARCHAR(10),
        OBJECT_NAME VARCHAR(30) PRIMARY KEY)')
  END

IF NOT EXISTS (SELECT *FROM OBJECT_METADATA  WHERE OBJECT_NAME = 'CRM_USERS' AND OBJECT_TYPE='TABLE')
  BEGIN     
	CREATE TABLE [dbo].[CRM_USERS](
	[USER_UID] [int] NOT NULL PRIMARY KEY IDENTITY(1000,1),
	[ACTIVE] [bit] NOT NULL,
	[CREATED_BY] [int] NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[DESCRIPTION] [varchar](1000) NULL,
	[EMAIL] [varchar](50) NOT NULL UNIQUE,
	[IMAGE_UID] [int] NULL,
	[MOBILE_NO] [bigint] NOT NULL,
	[MOBILE_PREFIX] [int] NOT NULL,
	[MODIFIED_BY] [int] NOT NULL,
	[MODIFIED_DATE] [datetime] NOT NULL,
	[NAME] [varchar](50) NOT NULL,
	[PASSWORD] [varchar](20) NOT NULL,
	[USER_ROLE] [varchar](255) NOT NULL
)
	  
  END  
IF NOT EXISTS (SELECT *FROM OBJECT_METADATA  WHERE OBJECT_NAME = 'CRM_USERS' AND OBJECT_TYPE='TABLE')
  BEGIN
    EXECUTE('INSERT INTO OBJECT_METADATA (OBJECT_UID,OBJECT_TYPE,OBJECT_NAME) VALUES(1,''TABLE'',''CRM_USERS'')')
END





-- ************************************** [CUSTOMER TABLE]****************************************************
IF NOT EXISTS (SELECT *FROM OBJECT_METADATA  WHERE OBJECT_NAME = 'PERMISSION' AND OBJECT_TYPE='TABLE')
  BEGIN     
	CREATE TABLE [dbo].[PERMISSION](
	[PERMISSION_UID] [int] IDENTITY(1,1) PRIMARY KEY,
	[USER_UID] [int] NOT NULL,
	[PERMISSION_NAME] [varchar](100) NOT NULL,
	[DESCRIPTION] [varchar](100) NOT NULL
	)	  
  END  
IF NOT EXISTS (SELECT *FROM OBJECT_METADATA  WHERE OBJECT_NAME = 'PERMISSION' AND OBJECT_TYPE='TABLE')
  BEGIN
    EXECUTE('INSERT INTO OBJECT_METADATA (OBJECT_UID,OBJECT_TYPE,OBJECT_NAME) VALUES(1,''TABLE'',''PERMISSION'')')
  END  
    
    


-- ************************************** [CUSTOMER TABLE]****************************************************
IF NOT EXISTS (SELECT *FROM OBJECT_METADATA  WHERE OBJECT_NAME = 'CUSTOMER' AND OBJECT_TYPE='TABLE')
  BEGIN  
CREATE TABLE [CUSTOMER]
(
 [CUSTOMER_UID]       int identity (100,1) PRIMARY KEY,
 [FIRST_NAME]         varchar(30) ,
 [LAST_NAME]          varchar(30) ,
 [CUSTOMER_STAGE]     varchar(30) NOT NULL ,
 [ASSIGNED_TO]        int,
 [COUNTRY]            varchar(30),
 [CURRENCY]           varchar(5),
 [REVENUE_POTENTIAL]  int NOT NULL ,
 [SERVICE_INTERESTED] varchar(50),
 [DESCRIPTION]        varchar(2000),
 [CREATED_BY]         int NOT NULL ,
 [CREATED_DATE]       datetime NOT NULL default getdate() ,
 [MODIFIED_BY]        int NOT NULL ,
 [MODIFIED_DATE]      datetime NOT NULL default getdate() 
)
END
IF NOT EXISTS (SELECT *FROM OBJECT_METADATA  WHERE OBJECT_NAME = 'CUSTOMER' AND OBJECT_TYPE='TABLE')
  BEGIN
  EXECUTE('INSERT INTO OBJECT_METADATA (OBJECT_UID,OBJECT_TYPE,OBJECT_NAME) VALUES(3,''TABLE'',''CUSTOMER'')')
END